### ISSUE TITLE
Any chance of update to 7.2?

### ISSUE THREAD

**Issue by kitrodian** [5Avian/proxvc#5]
Tried taking a crack at updating this to 7.2 myself. Didn't go particularly well due to a ton of mappings being changed, and I'm woefully under-experienced to deal with that.
I'd like to see this mod updated properly :)

**Comment by 5Avian** [comment]
cool to know that there's interest in an updated version of this mod. there's still a bunch of things i wanna do before i release a new version, but i'll try to update it when i have time :)

**Comment by 5Avian** [comment]
check modrinth, bta-modding or the releases. version 1.5.1 (2840399e1505359d7a904949a0b522bf1de0f1d8) has been released for BTA! 7.2
